### ISSUE TITLE
Reading PivotTable txt file

### ISSUE THREAD

**Issue by mxposed** [bmbolstad/affyio#5]
Hello. I wonder is there a way (or a guide) how to read pivot table txt data (GCOS output) instead of CEL file to create the AffyBatch object?

The fields in the file are: 
  * Stat Pairs	
  * Stat Pairs Used	
  * Signal	
  * Detection	
  * Detection p-value	
  * Descriptions

As far as I understand, this has all the information that is found in the CEL file (with some derived numbers)? Except experiment metadata which is a separate txt file

Thank you

**Comment by bmbolstad** [comment]
Short answer: No

Long answer: that’s not data from a CEL file.  That looks more like data from a CHP file which would be more processed than a CEL file.

**Comment by mxposed** [comment]
Thank you for a super fast answer! What would you recommend?

As far as I understand I still have the data that is needed to run `rma`?

**Comment by bmbolstad** [comment]
I would have to examine that data to be 100% certain, but I think your data has probably already had some sort of analysis procedure applied to it.  So past the point where you would do RMA (or rather GCOS has used some alternative procedure)

**Comment by mxposed** [comment]
Ok thank you. If you have time: which check would you run on the data? I can run them to check which normalization was used

**Comment by bmbolstad** [comment]
This is not really an issue with affyio.
